spring:
  application:
    name: security issue tracker
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/issues
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

management:
  security:
    enabled: false
security:
  basic:
    enabled: true

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG